function map = createMediumWarehouseMap(resolution)
%CREATEMEDIUMWAREHOUSEMAP Ban do 12 x 12 m voi nhieu day ke song song.
map = initializeWarehouseMap('MEDIUM_WAREHOUSE', 12, 12, resolution, ...
    'Kho trung binh voi ke song song va ba loi di ngang.');
o = map.occupancy;
xPositions = [2.0 4.4 6.8 9.2];
ySegments = [1.0 2.0; 4.2 2.0; 7.6 1.8; 10.6 0.4];
for x = xPositions
    for j = 1:size(ySegments,1)
        o = addRectangleObstacle(o, resolution, ...
            [x ySegments(j,1) 0.6 ySegments(j,2)]);
    end
end
o = addRectangleObstacle(o, resolution, [10.5 4.4 0.5 2.6]);
map.occupancy = o;
map.startGoalPairs = [ ...
    createScenario('CROSS_WAREHOUSE', [0.7 0.7], [11.3 11.3]), ...
    createScenario('LONG_AISLE', [3.5 0.7], [3.5 11.3]), ...
    createScenario('THROUGH_CROSS_AISLES', [0.7 5.1], [11.3 8.7]), ...
    createScenario('RACK_SIDE_CORNERS', [5.7 1.1], [8.1 10.1]), ...
    createScenario('MULTIPLE_ROUTES', [0.7 10.1], [11.3 1.1])];
end
