function map = createSmallWarehouseMap(resolution)
%CREATESMALLWAREHOUSEMAP Ban do 7 x 7 m co khoang mo, chu L va loi hep.
map = initializeWarehouseMap('SMALL_WAREHOUSE', 7, 7, resolution, ...
    'Kho nho co vat can trung tam, goc chu L va hanh lang hep.');
o = map.occupancy;
o = addRectangleObstacle(o, resolution, [2.7 2.5 1.4 1.4]);
o = addRectangleObstacle(o, resolution, [0.8 4.8 2.0 0.4]);
o = addRectangleObstacle(o, resolution, [0.8 4.8 0.4 1.3]);
o = addRectangleObstacle(o, resolution, [4.8 0.8 0.4 2.2]);
o = addRectangleObstacle(o, resolution, [5.9 2.0 0.4 2.8]);
map.occupancy = o;
map.startGoalPairs = [ ...
    createScenario('LONG_DIAGONAL', [0.7 0.7], [6.3 6.3]), ...
    createScenario('NARROW_PASSAGE', [4.3 0.7], [5.5 5.5]), ...
    createScenario('OPEN_TO_L_CORNER', [3.9 6.3], [0.7 4.1]), ...
    createScenario('AROUND_CENTER', [1.7 1.7], [5.3 4.7]), ...
    createScenario('MULTI_ROUTE', [0.7 3.7], [4.3 0.7])];
end
