function map = createDenseRackWarehouseMap(resolution)
%CREATEDENSERACKWAREHOUSEMAP Ban do 15 x 12 m mat do ke cao.
map = initializeWarehouseMap('DENSE_RACK_WAREHOUSE', 15, 12, resolution, ...
    'Kho day dac voi loi phu hep va cac goc sat ke.');
o = map.occupancy;
xPositions = 1.7:1.75:13.95;
ySegments = [1.0 1.8; 4.2 1.6; 7.2 1.4; 10.0 1.0];
for x = xPositions
    for j = 1:size(ySegments,1)
        o = addRectangleObstacle(o, resolution, ...
            [x ySegments(j,1) 0.55 ySegments(j,2)]);
    end
end
map.occupancy = o;
map.startGoalPairs = [ ...
    createScenario('DENSE_DIAGONAL', [0.7 0.7], [13.1 11.3]), ...
    createScenario('NARROW_AISLE', [2.9 0.7], [2.9 11.3]), ...
    createScenario('LOW_CROSS_PASSAGE', [0.7 3.5], [13.1 3.5]), ...
    createScenario('UPPER_CROSS_PASSAGE', [13.1 9.1], [0.7 6.5]), ...
    createScenario('MANY_CLOSE_CORNERS', [4.7 1.1], [11.7 10.9])];
end
