function row = emptyResultRow()
%EMPTYRESULTROW Mau mot dong ket qua de single va batch cung schema.
row = struct( ...
    'MapName','', 'MapWidth',nan, 'MapHeight',nan, ...
    'GridRows',nan, 'GridColumns',nan, 'TotalCells',nan, ...
    'FreeCells',nan, 'ObstacleDensity',nan, 'ScenarioName','', ...
    'AlgorithmRevision','', 'RobotProfile','', ...
    'RobotProfileMeasured',false, ...
    'Method','', 'Planner','', 'AStarTurnPenalty',nan, ...
    'AStarTurnCostRatio',nan, ...
    'AStarExpandedNodes',nan,'AStarPathCost',nan, ...
    'StartX',nan, 'StartY',nan, 'GoalX',nan, 'GoalY',nan, ...
    'AStarPlanningTime',nan, 'AStarPlanningTimeStd',nan, ...
    'AStarPlanningTimeMin',nan, 'AStarPlanningTimeMax',nan, ...
    'CornerDetectionTime',nan, 'FootprintCheckTime',nan, ...
    'ManeuverSelectionTime',nan, 'CornerOptimizationTime',nan, ...
    'CornerOptimizationTimeStd',nan, 'SimulationComputationTime',nan, ...
    'TotalAlgorithmTime',nan, 'TotalAlgorithmTimeStd',nan, ...
    'TotalAlgorithmTimeMin',nan, 'TotalAlgorithmTimeMax',nan, ...
    'NumberOfRawWaypoints',nan, 'NumberOfReducedWaypoints',nan, ...
    'NumberOfCorners',nan, 'NumberOfArcCandidates',nan, ...
    'NumberOfArcCorners',nan, 'NumberOfPivotCorners',nan, ...
    'NumberOfRejectedArcCandidates',nan, ...
    'ReferencePathLength',nan, 'ActualPathLength',nan, ...
    'CompletionTime',nan, 'NumberOfFullStops',nan, ...
    'TotalStoppedTime',nan, 'TotalPivotAngle',nan, ...
    'AverageLinearVelocity',nan, 'PositionRMSE',nan, 'HeadingRMSE',nan, ...
    'MinimumClearance',nan, 'Jv',nan, 'Jomega',nan, ...
    'MaximumLeftWheelVelocity',nan, 'MaximumRightWheelVelocity',nan, ...
    'LimitViolationCount',nan, 'CollisionCount',nan, ...
    'TimePerMeter',nan, 'StopsPerCorner',nan, ...
    'OptimizationTimePerCorner',nan, 'JvPerMeter',nan, ...
    'JomegaPerMeter',nan, 'ArcSelectionRate',nan, ...
    'TaskCompletionRate',nan, 'Success',false, 'ErrorMessage','');
end
