function row = evaluatePostprocessorRun(planner,method,signature,inputPath, ...
        processedPath,reference,simulation,decisions,info,map,scenario,config)
%EVALUATEPOSTPROCESSORRUN Metric hinh hoc, dong hoc, tracking va an toan.
tracking=computeTrackingMetrics(simulation,reference,decisions,config);
geometry=referenceGeometryMetrics(reference);
inputLength=sum(hypot(diff(inputPath(:,1)),diff(inputPath(:,2))));
outputLength=sum(hypot(diff(processedPath(:,1)),diff(processedPath(:,2))));
fallbackUsed=readLogical(info,'footprintRollback')|| ...
    readLogical(info,'costmapRollback');
iterations=readNumeric(info,'iterations',0);
maximumDisplacement=readNumeric(info,'maximumDisplacement',nan);
row=struct('MapName',map.name,'ScenarioName',scenario.name, ...
    'Planner',planner.name,'PlannerImplementation',planner.implementation, ...
    'Postprocessor',method.name,'DisplayName',method.displayName, ...
    'Plugin',method.plugin,'Implementation',method.implementation, ...
    'AlgorithmRevision',config.algorithmRevision, ...
    'RobotProfile',config.robot.profileName, ...
    'RobotProfileMeasured',config.robot.measured, ...
    'Preprocessing',info.preprocessing, ...
    'InputPathSignature',signature,'SameInputPath',true, ...
    'PlanningTime',planner.planningTime,'ExpandedNodes',planner.expandedNodes, ...
    'InputPathPoints',size(inputPath,1),'InputPathLength',inputLength, ...
    'PostprocessSuccess',true,'PostprocessTime',info.postprocessTime, ...
    'CorePostprocessTime',readNumeric(info,'coreTime',nan), ...
    'Iterations',iterations,'FallbackUsed',fallbackUsed, ...
    'MaximumDisplacement',maximumDisplacement, ...
    'OutputPathPoints',size(processedPath,1),'OutputPathLength',outputLength, ...
    'MaximumCurvature',geometry.MaximumCurvature, ...
    'IntegratedSquaredCurvature',geometry.IntegratedSquaredCurvature, ...
    'HeadingVariation',geometry.HeadingVariation, ...
    'ArcManeuvers',geometry.ArcManeuvers, ...
    'PivotManeuvers',geometry.PivotManeuvers, ...
    'ReferencePathLength',tracking.ReferencePathLength, ...
    'ActualPathLength',tracking.ActualPathLength, ...
    'CompletionTime',tracking.CompletionTime, ...
    'NumberOfFullStops',tracking.NumberOfFullStops, ...
    'AverageLinearVelocity',tracking.AverageLinearVelocity, ...
    'PositionRMSE',tracking.PositionRMSE,'HeadingRMSE',tracking.HeadingRMSE, ...
    'MinimumClearance',tracking.MinimumClearance,'Jv',tracking.Jv, ...
    'Jomega',tracking.Jomega, ...
    'MaximumWheelVelocity',max(tracking.MaximumLeftWheelVelocity, ...
        tracking.MaximumRightWheelVelocity), ...
    'CollisionCount',tracking.CollisionCount, ...
    'LimitViolationCount',tracking.LimitViolationCount, ...
    'TaskSuccess',tracking.Success,'Notes',info.message);
end

function metrics=referenceGeometryMetrics(reference)
ds=hypot(diff(reference.x),diff(reference.y));
dtheta=abs(wrapAngle(diff(reference.theta)));
moving=ds>1e-8;curvature=zeros(size(ds));
curvature(moving)=dtheta(moving)./ds(moving);
if any(~moving&dtheta>1e-6),maximumCurvature=inf;
elseif isempty(curvature),maximumCurvature=0;
else,maximumCurvature=max(curvature);end
finiteCurvature=curvature;finiteCurvature(~isfinite(finiteCurvature))=0;
mode=reference.mode(:);arc=startsWith(mode,'ARC');pivot=startsWith(mode,'PIVOT');
metrics=struct('MaximumCurvature',maximumCurvature, ...
    'IntegratedSquaredCurvature',sum(finiteCurvature.^2.*ds), ...
    'HeadingVariation',sum(dtheta), ...
    'ArcManeuvers',sum(arc&[true;~arc(1:end-1)]), ...
    'PivotManeuvers',sum(pivot&[true;~pivot(1:end-1)]));
end
function value=readLogical(s,field)
value=isfield(s,field)&&logical(s.(field));
end
function value=readNumeric(s,field,defaultValue)
if isfield(s,field),value=s.(field);else,value=defaultValue;end
end
