function row = evaluateNav2ComparisonRun(plannerResult,reference,simulation, ...
        decisions,map,scenario,config,smoothingInfo)
%EVALUATENAV2COMPARISONRUN Tao mot dong metric chung cho moi planner.
if nargin<8
    smoothingInfo=struct('enabled',false,'maximumDisplacement',nan);
end
metrics=computeTrackingMetrics(simulation,reference,decisions,config);
path=plannerResult.path;
if isempty(path),searchLength=nan;else
    searchLength=sum(hypot(diff(path(:,1)),diff(path(:,2))));
end
mode=reference.mode(:);
arcMask=startsWith(mode,'ARC');pivotMask=startsWith(mode,'PIVOT');
arcStarts=arcMask&[true;~arcMask(1:end-1)];
pivotStarts=pivotMask&[true;~pivotMask(1:end-1)];
headingChanges=sum(arcStarts)+sum(pivotStarts);
ds=hypot(diff(reference.x),diff(reference.y));dtheta=abs(wrapAngle(diff(reference.theta)));
moving=ds>1e-8;curvature=zeros(size(ds));curvature(moving)=dtheta(moving)./ds(moving);
if any(~moving&dtheta>1e-6),maxCurvature=inf;else,maxCurvature=max(curvature,[],'omitnan');end
row=struct('MapName',map.name,'ScenarioName',scenario.name, ...
    'Planner',plannerResult.name,'Nav2Plugin',plannerResult.plugin, ...
    'Implementation',plannerResult.implementation,'PlanningSuccess',plannerResult.success, ...
    'CommonSmootherEnabled',smoothingInfo.enabled, ...
    'SmoothingMaxDisplacement',smoothingInfo.maximumDisplacement, ...
    'PlanningTime',plannerResult.planningTime,'ExpandedNodes',plannerResult.expandedNodes, ...
    'PathCost',plannerResult.pathCost,'SearchPathPoints',size(path,1), ...
    'SearchPathLength',searchLength,'HeadingChanges',headingChanges, ...
    'MaximumCurvature',maxCurvature,'ArcManeuvers',sum(arcStarts), ...
    'PivotManeuvers',sum(pivotStarts),'ReferencePathLength',metrics.ReferencePathLength, ...
    'ActualPathLength',metrics.ActualPathLength,'CompletionTime',metrics.CompletionTime, ...
    'NumberOfFullStops',metrics.NumberOfFullStops, ...
    'AverageLinearVelocity',metrics.AverageLinearVelocity, ...
    'PositionRMSE',metrics.PositionRMSE,'HeadingRMSE',metrics.HeadingRMSE, ...
    'MinimumClearance',metrics.MinimumClearance,'Jv',metrics.Jv,'Jomega',metrics.Jomega, ...
    'MaximumWheelVelocity',max(metrics.MaximumLeftWheelVelocity,metrics.MaximumRightWheelVelocity), ...
    'CollisionCount',metrics.CollisionCount,'LimitViolationCount',metrics.LimitViolationCount, ...
    'TaskSuccess',metrics.Success,'Notes',plannerNote(plannerResult.name));
end

function note=plannerNote(name)
switch upper(name)
    case 'NAVFN_DIJKSTRA',note='Day du, wavefront; path grid va nhieu pivot.';
    case 'NAVFN_ASTAR',note='Grid A* nhanh hon Dijkstra nho heuristic.';
    case 'SMAC_2D',note='A* 2D cost-aware; khong bao dam dong hoc SE2.';
    case 'THETA_STAR',note='Any-angle ngan; van co doi huong dot ngot tai dinh.';
    case 'SMAC_HYBRID',note='Core Dubins curvature-feasible; pivot chi o rotation-shim noi goal.';
    case 'SMAC_STATE_LATTICE',note='Primitive SE2 co arc va pivot cho robot vi sai.';
    otherwise,note='A* phat re + chon pivot/arc theo clearance va thoi gian.';
end
end
