function comparisonTable = plotAStarPlannerComparison(result,config)
%PLOTASTARPLANNERCOMPARISON Doi chieu A* goc va A* phat chuyen huong.
traditionalConfig=config;
traditionalConfig.plannerMode='TRADITIONAL_ASTAR';
improvedConfig=config;
improvedConfig.plannerMode='IMPROVED_TURN_PENALTY';
[traditional,traditionalInfo]=planGridPath(result.planningOccupancy, ...
    result.scenario.start,result.scenario.goal,traditionalConfig,false);
[improved,improvedInfo]=planGridPath(result.planningOccupancy, ...
    result.scenario.start,result.scenario.goal,improvedConfig,false);
traditionalReduced=removeCollinearPoints(traditional);
improvedReduced=removeCollinearPoints(improved);
comparisonTable=table( ...
    ["TRADITIONAL_ASTAR";"IMPROVED_TURN_PENALTY"], ...
    [size(traditional,1);size(improved,1)], ...
    [numel(detectCorners(traditionalReduced));numel(detectCorners(improvedReduced))], ...
    [traditionalInfo.expandedNodes;improvedInfo.expandedNodes], ...
    [traditionalInfo.pathCostCells;improvedInfo.pathCostCells], ...
    'VariableNames',{'Planner','RawWaypoints','Turns','ExpandedNodes','PathCost'});
disp(comparisonTable);
figure('Name','A* traditional vs improved','Color','w');
drawOccupancyMap(result.map);
plot(traditional(:,1),traditional(:,2),'c--','LineWidth',1.5, ...
    'DisplayName',sprintf('A* goc: %d goc',numel(detectCorners(traditionalReduced))));
plot(improved(:,1),improved(:,2),'m-','LineWidth',1.8, ...
    'DisplayName',sprintf('A* cai tien: %d goc',numel(detectCorners(improvedReduced))));
plot(result.scenario.start(1),result.scenario.start(2),'go','MarkerFaceColor','g');
plot(result.scenario.goal(1),result.scenario.goal(2),'rp','MarkerFaceColor','r');
legend('Location','bestoutside'); grid on;
[turnPenalty,penaltyDetails]=computeAStarTurnPenalty(config);
title(sprintf('Chi phi buoc re K2 = %.2f (phat them lambda = %.2f)', ...
    penaltyDetails.turnCostRatio,turnPenalty));
end
