function plotScalabilityResults(allResults)
%PLOTSCALABILITYRESULTS Ve bon quan he quy mo bang cac mau adaptive.
mask = string(allResults.Method)=="ADAPTIVE_PIVOT_OR_ARC" & ...
    ~isnan(allResults.TotalAlgorithmTime);
data = allResults(mask,:);
makeScatter(1,data.TotalCells,data.TotalAlgorithmTime, ...
    'Tong so cell','Tong thoi gian thuat toan (s)', ...
    'SCALABILITY - TotalAlgorithmTime');
makeScatter(2,data.NumberOfCorners,data.CornerOptimizationTime, ...
    'So goc','Thoi gian corner optimizer (s)', ...
    'SCALABILITY - CornerOptimizationTime');
makeScatter(3,data.NumberOfCorners,data.NumberOfArcCandidates, ...
    'So goc','So arc candidate','SCALABILITY - Arc candidates');
makeScatter(4,data.TotalCells,data.AStarPlanningTime, ...
    'Tong so cell','Thoi gian A* (s)','SCALABILITY - A*');
end

function makeScatter(index,x,y,xLabel,yLabel,plotTitle)
figure('Name',sprintf('SCALABILITY %d',index),'Color','w');
scatter(x,y,42,'filled'); grid on;
xlabel(xLabel); ylabel(yLabel); title(plotTitle);
end
