function comparisonResult = runNav2PlannerComparison(map,scenario,config,comparison)
%RUNNAV2PLANNERCOMPARISON Chay 6 baseline Nav2-style va phuong phap de xuat.
if ~isfield(map,'obstacleCenters')
    [map.obstacleRows,map.obstacleColumns]=find(map.occupancy);
    map.obstacleCenters=gridToWorld(map.obstacleRows,map.obstacleColumns,map.resolution);
end
planningOccupancy=inflateOccupancyGrid(map.occupancy,config.inflationRadius,map.resolution);
potential=computeCostmapPotential(planningOccupancy,map.resolution,comparison.costDecayDistance);
% Duong de xuat xac dinh huong start/goal chung cho cac planner SE2.
plannerTimer=tic;
[proposedRaw,proposedInfo]=planGridPath(planningOccupancy,scenario.start,scenario.goal, ...
    config,comparison.captureSearchTrace);
proposedAStarTime=toc(plannerTimer);
if ~proposedInfo.success,error('Khong tim duoc duong de xuat: %s',proposedInfo.message);end
startHeading=atan2(proposedRaw(2,2)-proposedRaw(1,2),proposedRaw(2,1)-proposedRaw(1,1));
goalHeading=atan2(proposedRaw(end,2)-proposedRaw(end-1,2), ...
    proposedRaw(end,1)-proposedRaw(end-1,1));
startPose=[scenario.start startHeading];goalPose=[scenario.goal goalHeading];
plannerResults=cell(numel(comparison.plannerNames),1);

plannerResults{1}=nav2GridPlanner(planningOccupancy,scenario.start,scenario.goal, ...
    map.resolution,'NAVFN_DIJKSTRA',potential,0,comparison.captureSearchTrace);
plannerResults{1}.plugin='nav2_navfn_planner::NavfnPlanner(use_astar=false)';
plannerResults{2}=nav2GridPlanner(planningOccupancy,scenario.start,scenario.goal, ...
    map.resolution,'NAVFN_ASTAR',potential,0,comparison.captureSearchTrace);
plannerResults{2}.plugin='nav2_navfn_planner::NavfnPlanner(use_astar=true)';
plannerResults{3}=nav2GridPlanner(planningOccupancy,scenario.start,scenario.goal, ...
    map.resolution,'SMAC_2D',potential,comparison.smac2DCostWeight,comparison.captureSearchTrace);
plannerResults{3}.plugin='nav2_smac_planner::SmacPlanner2D';
plannerResults{4}=thetaStarPlannerEquivalent(planningOccupancy,scenario.start,scenario.goal, ...
    map.resolution,potential,comparison.thetaCostWeight,comparison.captureSearchTrace);
plannerResults{5}=nav2SE2PlannerEquivalent(planningOccupancy,startPose,goalPose,map, ...
    config,comparison,'SMAC_HYBRID',comparison.captureSearchTrace);
plannerResults{6}=nav2SE2PlannerEquivalent(planningOccupancy,startPose,goalPose,map, ...
    config,comparison,'SMAC_STATE_LATTICE',comparison.captureSearchTrace);

reduced=removeCollinearPoints(proposedRaw);corners=detectCorners(reduced);
optimizerTimer=tic;
[proposedDecisions,~]=chooseManeuversForMethod(corners,map,config,'ADAPTIVE_PIVOT_OR_ARC');
optimizerTime=toc(optimizerTimer);
proposedReference=generateSpeedProfile( ...
    buildReferenceTrajectory(reduced,proposedDecisions,config),config);
% Mot duong thang khong co corner la nghiem hop le. Trong truong hop nay
% decisions la struct rong va khong co field "valid" de truy cap.
proposedDecisionsValid=isempty(proposedDecisions) || ...
    all([proposedDecisions.valid]);
proposedPlanner=struct('name','PROPOSED_ADAPTIVE','plugin','CUSTOM_MATLAB_PROPOSED', ...
    'implementation','PROPOSED','success',proposedDecisionsValid, ...
    'path',proposedRaw, ...
    'poses',[proposedReference.x proposedReference.y proposedReference.theta], ...
    'modes',{proposedReference.mode},'radii',proposedReference.radius, ...
    'trace',proposedInfo.trace,'planningTime',proposedAStarTime+optimizerTime, ...
    'expandedNodes',proposedInfo.expandedNodes,'pathCost',proposedInfo.pathCostCells, ...
    'message','OK');
plannerResults{7}=proposedPlanner;

runTemplate=struct('planner',struct(),'reference',struct(),'simulation',struct(), ...
    'decisions',struct([]),'smoothingInfo',struct(),'error','');
runs=repmat(runTemplate,numel(plannerResults),1);rows=struct([]);
for i=1:numel(plannerResults)
    planner=plannerResults{i};
    try
        if ~planner.success,error('%s',planner.message);end
        if strcmp(planner.name,'PROPOSED_ADAPTIVE')
            reference=proposedReference;decisions=proposedDecisions;
        else
            [reference,decisions]=plannerResultToReference(planner,map,config, ...
                comparison.commonSmoother.cornerMethod);
        end
        [reference,smoothingInfo]=smoothReferenceTrajectoryCommon( ...
            reference,map,config,comparison);
        simulation=simulateDifferentialDrive(reference,map,config);
        row=evaluateNav2ComparisonRun(planner,reference,simulation,decisions, ...
            map,scenario,config,smoothingInfo);
        if isempty(rows),rows=row;else,rows(end+1,1)=row;end %#ok<AGROW>
        runs(i)=struct('planner',planner,'reference',reference, ...
            'simulation',simulation,'decisions',decisions, ...
            'smoothingInfo',smoothingInfo,'error','');
    catch exception
        runs(i).planner=planner;runs(i).error=exception.message;
        row=failureRow(planner,map,scenario,exception.message);
        if isempty(rows),rows=row;else,rows(end+1,1)=row;end %#ok<AGROW>
    end
end
comparisonResult=struct('map',map,'scenario',scenario, ...
    'planningOccupancy',planningOccupancy,'runs',runs, ...
    'resultTable',struct2table(rows),'comparisonConfig',comparison);
end

function row=failureRow(planner,map,scenario,message)
row=struct('MapName',map.name,'ScenarioName',scenario.name,'Planner',planner.name, ...
    'Nav2Plugin',planner.plugin,'Implementation',planner.implementation, ...
    'PlanningSuccess',false,'CommonSmootherEnabled',false, ...
    'SmoothingMaxDisplacement',nan,'PlanningTime',planner.planningTime, ...
    'ExpandedNodes',planner.expandedNodes,'PathCost',planner.pathCost, ...
    'SearchPathPoints',0,'SearchPathLength',nan,'HeadingChanges',nan, ...
    'MaximumCurvature',nan,'ArcManeuvers',0,'PivotManeuvers',0, ...
    'ReferencePathLength',nan,'ActualPathLength',nan,'CompletionTime',nan, ...
    'NumberOfFullStops',nan,'AverageLinearVelocity',nan,'PositionRMSE',nan, ...
    'HeadingRMSE',nan,'MinimumClearance',nan,'Jv',nan,'Jomega',nan, ...
    'MaximumWheelVelocity',nan,'CollisionCount',nan,'LimitViolationCount',nan, ...
    'TaskSuccess',false,'Notes',['FAILED: ' message]);
end
