function result = runPathPostprocessorComparison( ...
        plannerName,map,scenario,config,comparison)
%RUNPATHPOSTPROCESSORCOMPARISON Co dinh planner/controller, doi smoother.
if ~isfield(map,'obstacleCenters')
    [map.obstacleRows,map.obstacleColumns]=find(map.occupancy);
    map.obstacleCenters=gridToWorld(map.obstacleRows,map.obstacleColumns, ...
        map.resolution);
end
config.adaptiveSelection=comparison.proposed;
[planner,planningOccupancy]=planPostprocessorInputPath(plannerName,map, ...
    scenario,config,comparison);
sharedPath=planner.path;
signature=pathSignature(sharedPath);
methodNames=comparison.postprocessorNames;
template=struct('method',struct(),'inputPath',zeros(0,2), ...
    'processedPath',zeros(0,2),'reference',struct(), ...
    'simulation',struct(),'decisions',struct([]), ...
    'postprocessInfo',struct(),'error','');
runs=repmat(template,numel(methodNames),1);rows=struct([]);
for i=1:numel(methodNames)
    inputCopy=sharedPath;
    try
        [reference,processedPath,decisions,info,method]= ...
            applyPathPostprocessor(methodNames{i},inputCopy, ...
            planningOccupancy,map,config,comparison);
        if ~isequaln(inputCopy,sharedPath)
            error('%s da sua path dau vao tai cho.',method.name);
        end
        simulation=simulateDifferentialDrive(reference,map,config);
        row=evaluatePostprocessorRun(planner,method,signature,sharedPath, ...
            processedPath,reference,simulation,decisions,info,map,scenario,config);
        runs(i)=struct('method',method,'inputPath',inputCopy, ...
            'processedPath',processedPath,'reference',reference, ...
            'simulation',simulation,'decisions',decisions, ...
            'postprocessInfo',info,'error','');
    catch exception
        method=fallbackMethod(methodNames{i});
        row=failureRow(planner,method,signature,sharedPath,map,scenario, ...
            exception.message,config);
        runs(i).method=method;runs(i).inputPath=inputCopy;
        runs(i).error=exception.message;
    end
    if isempty(rows),rows=row;else,rows(end+1,1)=row;end %#ok<AGROW>
end
fairness=verifyPostprocessorFairness(runs,sharedPath,config);
result=struct('map',map,'scenario',scenario,'planner',planner, ...
    'planningOccupancy',planningOccupancy,'sharedInputPath',sharedPath, ...
    'inputPathSignature',signature,'algorithmRevision',config.algorithmRevision, ...
    'timeComparisonConfig',config.timeComparison, ...
    'controllerConfig',config.controller, ...
    'robotConfig',config.robot,'runs',runs,'resultTable',struct2table(rows), ...
    'comparisonConfig',comparison,'fairness',fairness);
end

function signature=pathSignature(path)
index=(1:size(path,1)).';
signature=sprintf('N%d_X%.12f_Y%.12f_L%.12f',size(path,1), ...
    sum(index.*path(:,1)),sum(index.*path(:,2)), ...
    sum(hypot(diff(path(:,1)),diff(path(:,2)))));
end
function method=fallbackMethod(name)
name=upper(char(name));display=strrep(lower(name),'_',' ');
method=struct('name',name,'displayName',display,'plugin','UNKNOWN', ...
    'implementation','UNKNOWN');
end
function row=failureRow(planner,method,signature,inputPath,map,scenario,message,config)
inputLength=sum(hypot(diff(inputPath(:,1)),diff(inputPath(:,2))));
row=struct('MapName',map.name,'ScenarioName',scenario.name, ...
    'Planner',planner.name,'PlannerImplementation',planner.implementation, ...
    'Postprocessor',method.name,'DisplayName',method.displayName, ...
    'Plugin',method.plugin,'Implementation',method.implementation, ...
    'AlgorithmRevision',config.algorithmRevision, ...
    'RobotProfile',config.robot.profileName, ...
    'RobotProfileMeasured',config.robot.measured, ...
    'Preprocessing','UNKNOWN', ...
    'InputPathSignature',signature,'SameInputPath',true, ...
    'PlanningTime',planner.planningTime,'ExpandedNodes',planner.expandedNodes, ...
    'InputPathPoints',size(inputPath,1),'InputPathLength',inputLength, ...
    'PostprocessSuccess',false,'PostprocessTime',nan, ...
    'CorePostprocessTime',nan,'Iterations',nan, ...
    'FallbackUsed',false,'MaximumDisplacement',nan,'OutputPathPoints',0, ...
    'OutputPathLength',nan,'MaximumCurvature',nan, ...
    'IntegratedSquaredCurvature',nan,'HeadingVariation',nan, ...
    'ArcManeuvers',0,'PivotManeuvers',0,'ReferencePathLength',nan, ...
    'ActualPathLength',nan,'CompletionTime',nan,'NumberOfFullStops',nan, ...
    'AverageLinearVelocity',nan,'PositionRMSE',nan,'HeadingRMSE',nan, ...
    'MinimumClearance',nan,'Jv',nan,'Jomega',nan, ...
    'MaximumWheelVelocity',nan,'CollisionCount',nan, ...
    'LimitViolationCount',nan,'TaskSuccess',false,'Notes',['FAILED: ' message]);
end
