function report = verifyAdaptivePivotG2Regression()
%VERIFYADAPTIVEPIVOTG2REGRESSION Hoi quy cho cac sua loi P0/P1.
config=defaultCornerOptimizerConfig();
config.enablePlots=false;config.enableAnimation=false;
measured=config.robot;measured.profileName='REGRESSION_MEASURED';
measuredConfig=applyMeasuredRobotProfile(config,measured);
assert(measuredConfig.robot.measured&& ...
    strcmp(measuredConfig.robot.profileName,'REGRESSION_MEASURED'), ...
    'Khong ap dung duoc measured robot profile.');

straightX=linspace(0,1,51).';
straightProfile=timeParameterizeMovingPath([straightX zeros(size(straightX))], ...
    zeros(size(straightX)),config.robot.maxLinearSpeed*ones(size(straightX)), ...
    config.robot,0,0);
assert(straightProfile.valid&&straightProfile.linearSpeed(1)==0&& ...
    straightProfile.linearSpeed(end)==0, ...
    'Time parameterizer khong ho tro boundary speed bang 0.');

% Mot goc 90 do rong: moi ban kinh duoc dat trong cung common window.
map=initializeWarehouseMap('REGRESSION_OPEN',8,8,config.resolution, ...
    'Open map for Pivot-G2 regression');
path=[2 4;4 4;4 6];corner=detectCorners(path);
assert(numel(corner)==1,'Khong tao duoc goc hoi quy.');
decision=selectCornerManeuver(corner,map,config,'ADAPTIVE_PIVOT_OR_ARC');
valid=find([decision.arcCandidates.valid]);
assert(numel(valid)>=2,'Can it nhat hai G2 candidate hop le.');
assert(isfinite(decision.pivotTime)&&isfinite(decision.bestArcTime), ...
    'Common-window time phai huu han.');
windows=[decision.arcCandidates(valid).comparisonWindowDistance];
assert(max(windows)-min(windows)<1e-12, ...
    'Cac ban kinh dang bi so sanh tren cua so khac nhau.');
assert(abs(windows(1)-decision.pivot.comparisonWindowDistance)<1e-12, ...
    'Pivot va G2 khong dung cung common window.');
assert(strcmp(decision.pivot.timeDetails.model, ...
    'COMMON_WINDOW_TIME_PARAMETERIZED'),'Pivot van dung time model cu.');

selected=decision.arcCandidates(decision.bestArcIndex);
assert(selected.timeProfile.valid,'Selected G2 time profile khong hop le.');
assert(selected.timeProfile.maxAbsAngularAcceleration<= ...
    config.robot.maxAngularAcceleration*(1+1e-4), ...
    'Selected G2 vuot gioi han gia toc goc.');
assert(max(abs(selected.curvatureProfile([1 end])))<1e-8, ...
    'Transition khong dat curvature=0 tai endpoint.');
chord=hypot(diff(selected.poses(:,1)),diff(selected.poses(:,2)));
assert(max(chord)<=config.arcSampleSpacing*(1+1e-6), ...
    'Adaptive sampling khong giu duoc maximum chord.');

% Swept collision: hai endpoint an toan, nhung footprint quay qua 45 do va
% cham obstacle o huong cheo. Validation phai bat duoc mau trung gian.
sweepConfig=config;sweepConfig.robot.length=0.40;sweepConfig.robot.width=0.10;
sweepConfig.robot.clearanceSafe=0;sweepConfig.geometrySampleStep=0.04;
sweepMap=initializeWarehouseMap('SWEEP',2,2,0.02,'Rotation sweep');
sweepMap.occupancy=addRectangleObstacle(sweepMap.occupancy,0.02, ...
    [1.12 1.12 0.02 0.02]);
pose0=[1 1 0];pose90=[1 1 pi/2];
endpoint0=evaluatePoseSequenceSafety(pose0,sweepMap,sweepConfig);
endpoint90=evaluatePoseSequenceSafety(pose90,sweepMap,sweepConfig);
assert(endpoint0.safe, ...
    'Endpoint 0 do cua swept test phai an toan.');
assert(endpoint90.safe, ...
    'Endpoint 90 do cua swept test phai an toan.');
swept=evaluatePoseSequenceSafety([pose0;pose90],sweepMap,sweepConfig);
assert(~swept.safe,'Swept validation bo sot va cham giua hai endpoint.');

comparison=defaultPostprocessorComparisonConfig(config);
assert(~comparison.proposedRefinement.enabled, ...
    'Refinement pha G2 phai tat trong cau hinh benchmark chinh.');
report=struct('passed',true,'validCandidateCount',numel(valid), ...
    'selectedRadius',decision.selectedRadius,'pivotTime',decision.pivotTime, ...
    'bestG2Time',decision.bestArcTime,'sweptSamples',swept.samplesChecked, ...
    'refinementEnabled',comparison.proposedRefinement.enabled);
fprintf('ADAPTIVE PIVOT-G2 REGRESSION: PASS (%d valid candidates)\n',numel(valid));
end
