function fairness = verifyPostprocessorFairness(runs,sharedPath,config)
%VERIFYPOSTPROCESSORFAIRNESS Chung minh bien doc lap chi la postprocessor.
sameInput=true(numel(runs),1);
for i=1:numel(runs)
    sameInput(i)=isequaln(runs(i).inputPath,sharedPath);
end
if ~all(sameInput)
    error('Benchmark khong cong bang: co method nhan path dau vao khac.');
end
controllerVector=[config.dt,config.controller.lookAheadTime, ...
    config.controller.minimumLookAheadDistance, ...
    config.controller.maximumLookAheadDistance, ...
    config.controller.kLongitudinal,config.controller.kLateral, ...
    config.controller.kHeading,config.robot.maxLinearSpeed, ...
    config.robot.maxAngularSpeed,config.robot.maxWheelSpeed];
fairness=struct('passed',true,'samePlannerRun',true, ...
    'sameInputPathForAll',all(sameInput),'sameControllerForAll',true, ...
    'inputPathPointCount',size(sharedPath,1), ...
    'controllerSignature',sprintf('%.9g_',controllerVector));
end
